// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WherezIt.Infrastructure.Persistence;

#nullable disable

namespace WherezIt.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WherezItDbContext))]
    [Migration("20260902130000_UpdateWorkspaceAuditEventTypeConstraint")]
    partial class UpdateWorkspaceAuditEventTypeConstraint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WherezIt.Domain.Entities.WorkspaceAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("AllowedUserIds")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("allowed_user_ids");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("details_json");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("event_type");

                    b.Property<Guid>("InventoryNamespaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_namespace_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<string>("WorkspaceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("workspace_name");

                    b.HasKey("Id");

                    b.HasIndex("InventoryNamespaceId", "OccurredAt")
                        .HasDatabaseName("ix_workspace_audits_namespace_occurred");

                    b.HasIndex("WorkspaceId", "OccurredAt")
                        .HasDatabaseName("ix_workspace_audits_workspace_occurred");

                    b.ToTable("workspace_audits", null, t =>
                        {
                            t.HasCheckConstraint("ck_workspace_audits_event_type", "event_type IN ('WORKSPACE_CREATED', 'WORKSPACE_DELETED', 'LOCATION_CREATED', 'LOCATION_RENAMED', 'LOCATION_DELETED')");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
