// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using WherezIt.Infrastructure.Persistence;

#nullable disable

namespace WherezIt.Infrastructure.Migrations
{
    [DbContext(typeof(WherezItDbContext))]
    [Migration("20260902100000_AddSiblingLocationUniquenessIndexes")]
    partial class AddSiblingLocationUniquenessIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
